### ISSUE TITLE
Needs Python 3 Support

### ISSUE THREAD

**Issue by arthanson** [ecometrica/django-multisite#14]
Not compatible with Python 3

In middleware.py line 4:
from urlparse import urlsplit, urlunsplit
ImportError: No module named 'urlparse'

According to https://docs.python.org/2/library/urlparse.html:

```
The urlparse module is renamed to urllib.parse in Python 3.
```

**Comment by pydanny** [comment]
I think this issue can be closed as resolved:

* https://github.com/ecometrica/django-multisite/blob/master/setup.py#L39
* We're using it with Python 3.5 in production 😉

**Comment by kousu** [comment]
Hi there. It looks like this specific bug was fixed in https://github.com/ecometrica/django-multisite/commit/7f2f55b3cb1b17537d28ca8fd5a0bd255619d924. I am going to keep this issue open until I am not convinced we have full python3 support.

@pydanny, you are running this under python3? Without making any patches to get it there? We are not on python3 yet so our only tests are the unit tests.

**Comment by pydanny** [comment]
Yes, we run in production with Python 3. We've not had any problems. I would say this issue can be closed.
