### ISSUE TITLE
Remove md5

### ISSUE THREAD

**Issue by kousu** [ecometrica/django-multisite#42]
md5 is super deprecated, yet we [have it in our code](https://github.com/ecometrica/django-multisite/blob/113dc87fcd69ecb86b8dd7a993a4eeff80989c2d/multisite/middleware.py#L31). It isn't being used for anything security-related, but that begs the question of why it is used at all.

From my reading it is being used as a hand-rolled way of writing [`__hash__()`](https://docs.python.org/3/reference/datamodel.html#object.__hash__). If that's so, we should gut that and literally use `__hash__()`.

**Comment by JordanReiter** [comment]
md5 is only deprecated for security purposes. It's perfectly fine to use md5 from hashlib for creating a unique hash. 

In this case, however, I'm really not sure why the cache key is being created in this way at all. You may as well just use the actual hostname instead, since it's already a string to begin with and there is (at worst) a one-to-one correspondence between a hostname and its hashed version.

But just to be clear: the reason md5 is deprecated in Django is because it exists as a built-in in later versions of Python, not because there's anything wrong per-se with md5. Yes, md5 should no longer be used for security purposes, but as a very fast hashing function it's definitely better than Python's built-in `hash`. Python's hash function is not intended to create reliably unique pointers to values. The hash is just an 8 byte integer; an md5 hash is 16 bytes. So md5 has half the number of potential collisions.

**Comment by rebkwok** [comment]
Closing for the reasons outlined by @JordanReiter above
